sudo: false
language: ruby
bundler_args: --path vendor/bundle --jobs=3 --retry=3
script: bundle exec rspec
cache: bundler

before_install:
  - gem install bundler
  - bundle config --local without local_development yard guard
rvm:
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - jruby-9.1.9.0
  - "rbx-3"
matrix:
  allow_failures:
    - rvm: rbx-3
  fast_finish: true
